package com.rental.shortrental.audit;

public enum AuditAction {
    BOOKING_CREATED,
    GUEST_CREATED,
    GUEST_DATA_LINK_ISSUED,
    GUEST_DATA_SUBMITTED,
    GUEST_PHOTOS_UPLOADED,
    PASSPORT_VIEWED,
    PASSPORT_VERIFIED,
    PASSPORT_REJECTED,
    DOCUMENT_CREATED,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_DELETED,
    DOCUMENT_TEMPLATE_CREATED,
    DOCUMENT_TEMPLATE_UPDATED,
    DOCUMENT_TEMPLATE_DELETED,
    RETENTION_POLICY_UPDATED,
    RETENTION_PURGE_RUN
}
